name: Push Chocolatey package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      CHOCOLATEY_API_KEY:
        required: true

jobs:
  chocolatey:
    name: Pack and push
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Windows executable
        uses: actions/download-artifact@v4
        with:
          name: l5x-lint-windows-x86_64.exe
          path: installers/choco/tools

      - name: Stamp version
        shell: pwsh
        run: |
          $VERSION = "${{ inputs.version }}"

          $nuspec = Get-Content "installers/choco/l5x-lint.nuspec" -Raw
          $nuspec = $nuspec -replace '<version>.*</version>', "<version>${VERSION}</version>"
          Set-Content -Path "installers/choco/l5x-lint.nuspec" -Value $nuspec -Encoding utf8

      - name: Pack and push
        shell: pwsh
        run: |
          cd installers/choco
          choco pack
          $nupkg = Get-ChildItem -Filter "*.nupkg" | Select-Object -First 1
          choco push $nupkg.Name --source https://push.chocolatey.org/ --api-key ${{ secrets.CHOCOLATEY_API_KEY }}
