name: CI

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Check formatting
        run: uv run ruff format --check .
        shell: bash

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Run linter
        run: uv run ruff check .
        shell: bash

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Run tests
        run: uv run pytest tests/ -v
        shell: bash
